force-app/main/default/objects/Major_Sport_Venues__c/Major_Sport_Venues__c.object-meta.xml
<CustomObject>
    <label>Major_Sport_Venues</label>
    <nameField>
        <label>Major_Sport_Venues</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Major_Sport_Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Major_Sport_Venues__c/fields/ADDRESS__c.field-meta.xml
<CustomField>
    <fullName>ADDRESS__c</fullName>
    <label>ADDRESS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Major_Sport_Venues__c/fields/CITY__c.field-meta.xml
<CustomField>
    <fullName>CITY__c</fullName>
    <label>CITY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Major_Sport_Venues__c/fields/COLOR__c.field-meta.xml
<CustomField>
    <fullName>COLOR__c</fullName>
    <label>COLOR</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Major_Sport_Venues__c/fields/NAICS_DESC__c.field-meta.xml
<CustomField>
    <fullName>NAICS_DESC__c</fullName>
    <label>NAICS_DESC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Major_Sport_Venues__c/fields/STATE__c.field-meta.xml
<CustomField>
    <fullName>STATE__c</fullName>
    <label>STATE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BaseballSearchController.cls
public with sharing class BaseballSearchController {
    @AuraEnabled
    public static List<Major_Sport_Venues__c> searchBaseballs ( String searchTerm ) {
        List<Major_Sport_Venues__c> baseball = new List<Major_Sport_Venues__c>();
        if ( String.isNotBlank( searchTerm ) ) 
            
        {
            List<List<SObject>> searchResults = [
                FIND :searchTerm
                RETURNING Major_Sport_Venues__c(
                    NAME__c,
                    ADDRESS__c, CITY__c,
                    STATE__c, NAICS_DESC__c, COLOR__c
                    ORDER BY NAME__c
                    LIMIT 10
                )
            ];
            
            baseball = searchResults[0];
        }
        return baseball;
    }
}